# Generated by Django 5.2.14 on 2026-06-15 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0004_alter_notification_options_and_more'),
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_acheteur", models.CharField(max_length=100)),
                ("prenom_acheteur", models.CharField(max_length=100)),
                ("adresse_livraison", models.TextField()),
                ("telephone", models.CharField(max_length=20)),
                ("date_commande", models.DateTimeField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("CONFIRMEE", "Confirmée"),
                            ("REFUSEE", "Refusée"),
                            ("EN_COURS_DE_LIVRAISON", "En cours de livraison"),
                            ("LIVREE", "Livrée"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="EN_ATTENTE",
                        max_length=30,
                    ),
                ),
                (
                    "acheteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commandes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "livre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commandes_associees",
                        to="books.livre",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_commande",
            },
        ),
        migrations.CreateModel(
            name="Livraison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_livraison",
                    models.CharField(
                        choices=[
                            ("REMISE_EN_MAIN_PROPRE", "Remise en main propre"),
                            ("LIVRAISON_DOMICILE", "Livraison à domicile"),
                        ],
                        max_length=30,
                    ),
                ),
                ("statut", models.CharField(max_length=50)),
                (
                    "numero_suivi",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_estimee", models.DateField(blank=True, null=True)),
                (
                    "date_livraison_effective",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "commande",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livraison",
                        to="orders.commande",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_livraison",
            },
        ),
            ],
        ),
    ]
