# Generated by Django 5.2.14 on 2026-06-15 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0004_alter_notification_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("telephone", models.CharField(blank=True, default="", max_length=20)),
                ("ville", models.CharField(blank=True, default="", max_length=100)),
                ("est_actif", models.BooleanField(default=True)),
                ("est_banni", models.BooleanField(default=False)),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
                ("derniere_connexion", models.DateTimeField(auto_now=True)),
                ("est_acheteur", models.BooleanField(default=True)),
                ("est_vendeur", models.BooleanField(default=False)),
                ("est_administrateur", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_profile",
            },
        ),
            ],
        ),
    ]
