# Generated by Django 5.2.14 on 2026-06-14 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_signalement_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('MESSAGE', 'Message'), ('COMMANDE', 'Commande'), ('COMMANDE_ACCEPTEE', 'Commande acceptée'), ('COMMANDE_REFUSEE', 'Commande refusée'), ('FAVORI_DEVENU_DISPONIBLE', 'Favori devenu disponible'), ('ALERTE_SYSTEME', 'Alerte système'), ('ADMIN_MESSAGE', 'Message admin'), ('SIGNALEMENT_ACCEPTE', 'Signalement accepté'), ('SIGNALEMENT_REFUSE', 'Signalement refusé')], max_length=30),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='livre_signale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='marketplace.livre'),
        ),
    ]
