# Generated by Django 5.2.14 on 2026-06-15 00:54

from django.db import migrations


MODEL_OWNERS = {
    "profile": "accounts",
    "livre": "books",
    "imagelivre": "books",
    "favori": "books",
    "evaluation": "books",
    "commande": "orders",
    "livraison": "orders",
    "message": "messaging",
    "signalement": "moderation",
    "notification": "notifications",
}


def move_content_types(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model, app_label in MODEL_OWNERS.items():
        ContentType.objects.filter(app_label="marketplace", model=model).update(app_label=app_label)


def restore_content_types(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model, app_label in MODEL_OWNERS.items():
        ContentType.objects.filter(app_label=app_label, model=model).update(app_label="marketplace")


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_notification_options_and_more'),
        ('accounts', '0001_initial'),
        ('books', '0002_initial'),
        ('orders', '0001_initial'),
        ('messaging', '0001_initial'),
        ('moderation', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(move_content_types, restore_content_types),
            ],
            state_operations=[
        migrations.RemoveField(
            model_name="commande",
            name="acheteur",
        ),
        migrations.RemoveField(
            model_name="commande",
            name="livre",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="commande",
        ),
        migrations.RemoveField(
            model_name="evaluation",
            name="commande",
        ),
        migrations.AlterUniqueTogether(
            name="evaluation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="evaluation",
            name="evaluateur",
        ),
        migrations.RemoveField(
            model_name="evaluation",
            name="evalue",
        ),
        migrations.AlterUniqueTogether(
            name="favori",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="favori",
            name="acheteur",
        ),
        migrations.RemoveField(
            model_name="favori",
            name="livre",
        ),
        migrations.RemoveField(
            model_name="imagelivre",
            name="livre",
        ),
        migrations.RemoveField(
            model_name="livre",
            name="vendeur",
        ),
        migrations.RemoveField(
            model_name="signalement",
            name="livre_signale",
        ),
        migrations.RemoveField(
            model_name="message",
            name="destinataire",
        ),
        migrations.RemoveField(
            model_name="message",
            name="expediteur",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="utilisateur",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="signalement",
            name="signaleur",
        ),
        migrations.RemoveField(
            model_name="signalement",
            name="traite_par",
        ),
        migrations.RemoveField(
            model_name="signalement",
            name="utilisateur_signale",
        ),
        migrations.DeleteModel(
            name="Livraison",
        ),
        migrations.DeleteModel(
            name="Commande",
        ),
        migrations.DeleteModel(
            name="Evaluation",
        ),
        migrations.DeleteModel(
            name="Favori",
        ),
        migrations.DeleteModel(
            name="ImageLivre",
        ),
        migrations.DeleteModel(
            name="Livre",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.DeleteModel(
            name="Signalement",
        ),
            ],
        ),
    ]
