# Generated by Django 5.2.14 on 2026-06-15 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0004_alter_notification_options_and_more'),
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name="Signalement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raison", models.TextField()),
                ("date_signalement", models.DateTimeField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("ACCEPTED", "Accepté"),
                            ("REJECTED", "Rejeté"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("message_admin", models.TextField(blank=True, default="")),
                ("date_traitement", models.DateTimeField(blank=True, null=True)),
                (
                    "livre_signale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signalements",
                        to="books.livre",
                    ),
                ),
                (
                    "signaleur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signalements_faits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "traite_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signalements_traites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "utilisateur_signale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accuse_de",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_signalement",
            },
        ),
            ],
        ),
    ]
