# Generated by Django 5.2.14 on 2026-06-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0004_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.IntegerField()),
                ("commentaire", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "marketplace_evaluation",
            },
        ),
        migrations.CreateModel(
            name="Favori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "marketplace_favori",
            },
        ),
        migrations.CreateModel(
            name="ImageLivre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="livres/images/")),
                ("est_principale", models.BooleanField(default=False)),
                ("date_upload", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "marketplace_imagelivre",
            },
        ),
        migrations.CreateModel(
            name="Livre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("auteur", models.CharField(max_length=255)),
                ("matiere", models.CharField(max_length=100)),
                ("niveau", models.CharField(max_length=100)),
                (
                    "prix",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "type_livre",
                    models.CharField(default="Manuel Scolaire", max_length=100),
                ),
                (
                    "type_annonce",
                    models.CharField(
                        choices=[
                            ("VENTE", "Vente"),
                            ("DON", "Don"),
                            ("ECHANGE", "Échange"),
                        ],
                        default="VENTE",
                        max_length=20,
                    ),
                ),
                ("date_publication", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("DISPONIBLE", "Disponible"),
                            ("VENDU", "Vendu"),
                            ("ARCHIVEE", "Archivée"),
                        ],
                        default="DISPONIBLE",
                        max_length=20,
                    ),
                ),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("NEUF", "Neuf"),
                            ("BON", "Bon état"),
                            ("USAGE", "Usagé"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "marketplace_livre",
                "ordering": ["-date_creation"],
            },
        ),
            ],
        ),
    ]
