# Generated by Django 5.2.14 on 2026-06-15 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.AddField(
            model_name="evaluation",
            name="commande",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluations",
                to="orders.commande",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="evaluateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluations_donnees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="evalue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluations_recues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="favori",
            name="acheteur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favoris",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="livre",
            name="vendeur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="livres_a_vendre",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="imagelivre",
            name="livre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="books.livre",
            ),
        ),
        migrations.AddField(
            model_name="favori",
            name="livre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorises_par",
                to="books.livre",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="evaluation",
            unique_together={("evaluateur", "commande")},
        ),
        migrations.AlterUniqueTogether(
            name="favori",
            unique_together={("acheteur", "livre")},
        ),
            ],
        ),
    ]
