# Generated by Django 5.2.14 on 2026-06-15 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0004_alter_notification_options_and_more'),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenu", models.TextField()),
                ("lien", models.CharField(blank=True, default="", max_length=255)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("est_lue", models.BooleanField(default=False)),
                (
                    "type_notification",
                    models.CharField(
                        choices=[
                            ("MESSAGE", "Message"),
                            ("COMMANDE", "Commande"),
                            ("COMMANDE_ACCEPTEE", "Commande acceptée"),
                            ("COMMANDE_REFUSEE", "Commande refusée"),
                            ("FAVORI_DEVENU_DISPONIBLE", "Favori devenu disponible"),
                            ("ALERTE_SYSTEME", "Alerte système"),
                            ("ADMIN_MESSAGE", "Message admin"),
                            ("SIGNALEMENT_ACCEPTE", "Signalement accepté"),
                            ("SIGNALEMENT_REFUSE", "Signalement refusé"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="orders.commande",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_notification",
                "ordering": ["-date_creation"],
            },
        ),
            ],
        ),
    ]
